name: 'jest-coverage-report'
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize, ready_for_review]
jobs:
  coverage:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          test-script: npx jest --coverage --silent --testLocationInResults --ci
          annotations: none
          custom-title: Coverage report for frontend
          skip-step: install
